SLIDE_SOURCES := $(wildcard Course*/slides.md)
SLIDE_TARGETS := $(SLIDE_SOURCES:.md=.pptx)

# figures generated by scripts/make_figures.py, tracked so the .pptx rebuilds when they do
FIGURES := $(addprefix Course01/img/,noise.png missingness.png imbalance.png shift.png shortcut.png)

.PHONY: slides figures clean-slides clean-figures
slides: $(SLIDE_TARGETS)

figures: $(FIGURES)

$(FIGURES): scripts/make_figures.py Course01/img/image2d_medical.jpg
	python3 scripts/make_figures.py Course01/img

Course01/slides.pptx: $(FIGURES)

%.pptx: %.md scripts/fit_pptx.py
	pandoc $< -o $@ --slide-level=2 --resource-path=$(dir $<)
	python3 scripts/fit_pptx.py $@

clean-slides:
	rm -f $(SLIDE_TARGETS)

clean-figures:
	rm -f $(FIGURES)
