SLIDE_SOURCES := $(wildcard Course*/slides*.md)
SLIDE_TARGETS := $(SLIDE_SOURCES:.md=.pptx)

# Course01: one figure per concept, all generated by scripts/make_figures_c01.py
# the medical concepts ship in two stages: <name>_q asks the room, <name> reveals;
# <name>_alt is the non-medical twin, single-stage
C01_STEMS := noise_q noise missingness_q missingness imbalance_q imbalance \
             shift_q shift shortcut_q shortcut \
             noise_alt errors_alt errors_alt_bis imbalance_alt shift_alt shortcut_alt \
             dsmap feedback \
             task_finance task_retail task_manufacturing task_climate task_energy \
             task_transport task_sport task_public task_science task_healthcare

C01_FIGURES := $(foreach f,$(C01_STEMS),Course01/img/$(f).png)

# Course02: one figure per concept, all generated by scripts/make_figures_c02.py
# first the feature engineering and missing-data half, then the "how models work" half
C02_STEMS := cyclical elapsed windows window_types lags \
             log_transform onehot standardize binning polynomial interaction \
             group_relative embedding \
             missing_map mechanisms mean_impute mice eq_rubin \
             map supervised tasks \
             linreg_fit linreg_which eq_mse linreg_loss linreg_gd linreg_multi \
             linreg_basis logistic eq_logistic linreg_limits \
             tree_questions tree_split impurity tree_grow tree_regression \
             tree_overfit tree_instability \
             forest_idea eq_forest_variance forest_variance forest_diagram \
             forest_boundary max_features forest_features forest_correlation \
             forest_ntrees \
             boosting_stages bagging_vs_boosting boosting_overfit \
             svm_which svm_margin eq_svm svm_c svm_kernel \
             svm_similarity svm_kernel_zoo svm_kernels \
             zoo knn knn_predict knn_pitfalls

C02_FIGURES := $(foreach f,$(C02_STEMS),Course02/img/$(f).png)

# Course03: one figure per concept, all generated by scripts/make_figures_c03.py
C03_STEMS := nb_idea eq_gaussian_nb nb_fit nb_predict nb_boundary \
             recap train_test polyfit polyfit_curve bv_targets bv_fits \
             eq_bias_variance eq_erm eq_ridge_lasso eq_params eq_boosting \
             eq_xgboost eq_leaf_objective xgb_gh xgb_leaf_predict \
             xgb_leaf_score xgb_split_search \
             lgbm_bins lgbm_prefix lgbm_binned_scan lgbm_subtract lgbm_leafwise lgbm_goss \
             cat_example cat_chain cat_leak_why cat_leak cat_ordered_ts cat_shift cat_shift_why cat_ordered_boosting cat_ordered_cost cat_oblivious gbm_compare bv_decomposition double_descent \
             double_descent_measured dd_ridge interpolation lambda_curve \
             reg_path l1_l2_geometry reg_zoo tree_depth early_stopping \
             landscape_1d landscape_2d log_scale bo_surrogate bo_uncertainty \
             bo_prior_posterior bo_kernel bo_kernel_basis bo_noise bayesopt \
             acquisition search_compare optuna_history pruning \
             ensemble_avg_demo ensemble_correlation bagging_boundary \
             bagging_vs_boosting boosting_stages additive_model shrinkage \
             learning_rate stacking oof cv_schemes nested_cv concept_map

C03_FIGURES := $(foreach f,$(C03_STEMS),Course03/img/$(f).png)

# Course04: one figure per concept, all generated by scripts/make_figures_c04.py
C04_STEMS := auc_build auc_exception auc_monotone bernoulli_b \
             bernoulli_expfam brier_arithmetic brier_score calibrated_cv \
             calibration_leak cox_arithmetic cox_reading ece_arithmetic \
             ece_caveats expfam expfam_loss forest_boundary_bias glm \
             isotonic_fit log_loss_intro log_loss_likelihood margin_bias \
             model_zoo_calibration naive_bayes_bias platt_fit platt_flow \
             platt_vs_isotonic reliability_build reliability_choices \
             temperature_effect temperature_scaling \
             roc_vs_pr ppv_prevalence expected_utility \
             net_benefit_idea threshold_matrices dca_build \
             dca_curve dca_compare

C04_FIGURES := $(foreach f,$(C04_STEMS),Course04/img/$(f).png)

# CourseTS part 1 (structure): scripts/make_figures_cTS1.py
CTS1_STEMS := ts_zoo iid_broken components eq_decomposition add_vs_mult \
             moving_average ma_edges classical_decomp loess_build \
             loess_span stl stl_inner stl_outer eq_stationarity \
             stationary_zoo why_stationarity white_noise ar_intro \
             ar_memory random_walk_intro random_walk unit_root ar_p \
             backshift char_eq root_cases ma_intro spurious_regression \
             df_intuition df_test adf_test adf_recipe kpss_intuition \
             kpss_recipe adf_kpss differencing over_differencing \
             box_cox_why box_cox_lambda box_cox_choice lag_def eq_acf \
             acf_def acf_build acf_zoo acf_bands pacf_idea pacf_def \
             acf_pacf_signature ljung_box_intuition ljung_box_null \
             ljung_box_recipe

# CourseTS part 2 (forecasting and learning): scripts/make_figures_cTS2.py
CTS2_STEMS := forecast_task baselines naive_def naive_strong metrics \
             eq_mase backtest cv_wrong intervals arma_recap \
             arima_intuition eq_arima arima_pipeline sarima_problem sarima \
             box_jenkins ic_motivation aic_bic residual_diag arimax \
             arima_limits prophet_model prophet_trend prophet_shrinkage \
             fourier_seasonality prophet_events prophet_vs_arima

CTS1_FIGURES := $(foreach f,$(CTS1_STEMS),CourseTS/img/$(f).png)
CTS2_FIGURES := $(foreach f,$(CTS2_STEMS),CourseTS/img/$(f).png)

.PHONY: slides figures clean-slides clean-figures
slides: $(SLIDE_TARGETS)

figures: $(C01_FIGURES) $(C02_FIGURES) $(C03_FIGURES) $(C04_FIGURES) $(CTS1_FIGURES) $(CTS2_FIGURES)

$(C01_FIGURES): scripts/make_figures_c01.py Course01/img/image2d_medical.jpg
	python3 scripts/make_figures_c01.py Course01/img

$(C02_FIGURES): scripts/make_figures_c02.py
	python3 scripts/make_figures_c02.py Course02/img

$(C03_FIGURES): scripts/make_figures_c03.py
	python3 scripts/make_figures_c03.py Course03/img

$(C04_FIGURES): scripts/make_figures_c04.py
	python3 scripts/make_figures_c04.py Course04/img

$(CTS1_FIGURES): scripts/make_figures_cTS1.py scripts/cts_common.py
	python3 scripts/make_figures_cTS1.py CourseTS/img

$(CTS2_FIGURES): scripts/make_figures_cTS2.py scripts/cts_common.py
	python3 scripts/make_figures_cTS2.py CourseTS/img

Course01/slides.pptx: $(C01_FIGURES)
Course02/slides.pptx: $(C02_FIGURES)
Course03/slides.pptx: $(C03_FIGURES)
Course04/slides.pptx: $(C04_FIGURES)
CourseTS/slides1.pptx: $(CTS1_FIGURES)
CourseTS/slides2.pptx: $(CTS2_FIGURES)

%.pptx: %.md scripts/fit_pptx.py
	pandoc $< -o $@ --slide-level=2 --resource-path=$(dir $<)
	python3 scripts/fit_pptx.py $@

clean-slides:
	rm -f $(SLIDE_TARGETS)

clean-figures:
	rm -f $(C01_FIGURES) $(C02_FIGURES) $(C03_FIGURES) $(C04_FIGURES) $(CTS1_FIGURES) $(CTS2_FIGURES)
