SLIDE_SOURCES := $(wildcard Course*/slides*.md)
SLIDE_TARGETS := $(SLIDE_SOURCES:.md=.pptx)

# figures generated by scripts/make_figures.py, tracked so the .pptx rebuilds when they do
FIGURE_STEMS := noise missingness imbalance shift shortcut
# each figure ships in two stages: <name>_q.png asks the room, <name>.png reveals
FIGURES := $(foreach f,$(FIGURE_STEMS),Course01/img/$(f)_q.png Course01/img/$(f).png)
# the non-medical twin of each concept, single-stage
ALT_STEMS := noise errors imbalance shift shortcut
FIGURES += $(foreach f,$(ALT_STEMS),Course01/img/$(f)_alt.png)
FIGURES += Course01/img/errors_alt_bis.png
# section 3: the two argument diagrams and one task figure per field
FIGURES += Course01/img/dsmap.png Course01/img/feedback.png Course01/img/semester.png
TASK_STEMS := finance retail manufacturing climate energy transport sport public science healthcare
FIGURES += $(foreach f,$(TASK_STEMS),Course01/img/task_$(f).png)

# Course02 main deck: illustrations generated by scripts/make_figures_c02.py
C02_STEMS := cyclical elapsed windows window_types lags \
             log_transform onehot standardize binning polynomial interaction \
             group_relative embedding \
             missing_map mechanisms mean_impute mice eq_rubin
C02_FIGURES := $(foreach f,$(C02_STEMS),Course02/img/$(f).png)

# Course02 companion deck: one figure per concept, all from make_figures_c02b.py
C02B_STEMS := map supervised tasks \
              linreg_fit linreg_which eq_mse linreg_loss linreg_gd linreg_multi \
              linreg_basis logistic eq_logistic linreg_limits \
              tree_questions tree_split impurity tree_grow tree_regression \
              tree_overfit tree_instability \
              forest_idea eq_forest_variance forest_variance forest_diagram \
              forest_boundary max_features forest_features \
              forest_correlation \
              forest_ntrees \
              boosting_stages bagging_vs_boosting boosting_overfit \
              svm_which svm_margin eq_svm svm_c svm_kernel \
              svm_similarity svm_kernel_zoo svm_kernels \
              zoo knn knn_predict knn_pitfalls
C02B_FIGURES := $(foreach f,$(C02B_STEMS),Course02/img/$(f).png)

# Course03: one figure per concept, all generated by scripts/make_figures_c03.py
C03_STEMS := recap train_test polyfit polyfit_curve bv_targets bv_fits \
             eq_bias_variance eq_erm eq_ridge_lasso eq_params eq_boosting \
             eq_xgboost eq_leaf_objective xgb_gh xgb_leaf_predict \
             xgb_leaf_score xgb_split_search \
             lgbm_bins lgbm_prefix lgbm_binned_scan lgbm_subtract lgbm_leafwise lgbm_goss \
             cat_example cat_chain cat_leak_why cat_leak cat_ordered_ts cat_shift cat_shift_why cat_ordered_boosting cat_ordered_cost cat_oblivious gbm_compare bv_decomposition double_descent \
             double_descent_measured dd_ridge interpolation lambda_curve \
             reg_path l1_l2_geometry reg_zoo tree_depth early_stopping \
             landscape_1d landscape_2d log_scale bo_surrogate bo_uncertainty \
             bo_prior_posterior bo_kernel bo_kernel_basis bo_noise bayesopt \
             acquisition search_compare optuna_history pruning \
             ensemble_avg_demo ensemble_correlation bagging_boundary \
             bagging_vs_boosting boosting_stages additive_model shrinkage \
             learning_rate stacking oof cv_schemes nested_cv concept_map

C03_FIGURES := $(foreach f,$(C03_STEMS),Course03/img/$(f).png)

.PHONY: slides figures clean-slides clean-figures
slides: $(SLIDE_TARGETS)

figures: $(FIGURES) $(C02_FIGURES) $(C02B_FIGURES) $(C03_FIGURES)

$(FIGURES): scripts/make_figures.py Course01/img/image2d_medical.jpg
	python3 scripts/make_figures.py Course01/img

$(C02_FIGURES): scripts/make_figures_c02.py
	python3 scripts/make_figures_c02.py Course02/img

$(C02B_FIGURES): scripts/make_figures_c02b.py
	python3 scripts/make_figures_c02b.py Course02/img

$(C03_FIGURES): scripts/make_figures_c03.py
	python3 scripts/make_figures_c03.py Course03/img

Course01/slides.pptx Course01/slides-bis.pptx: $(FIGURES)
Course02/slides.pptx: $(C02_FIGURES)
Course02/slides-bis.pptx: $(C02B_FIGURES)
Course03/slides.pptx: $(C03_FIGURES)

%.pptx: %.md scripts/fit_pptx.py
	pandoc $< -o $@ --slide-level=2 --resource-path=$(dir $<)
	python3 scripts/fit_pptx.py $@

clean-slides:
	rm -f $(SLIDE_TARGETS)

clean-figures:
	rm -f $(FIGURES) $(C02_FIGURES) $(C02B_FIGURES) $(C03_FIGURES)
